tieba:
  tiebaName: 李毅
  tiebaTopUrl: http://tieba.baidu.com/f/like/furank?ie=utf-8&kw=
  tiebaContentUrl: http://tieba.baidu.com/f?ie=utf-8&kw=
  tiebaContentPageUrl: http://tieba.baidu.com/p/
  #5*50=250个帖子
  tiebaContentPageEndNum: 3
  tiebaImageUrl: http://imgsrc.baidu.com/forum/w%3D580/
  tiebaContentIdTopic: tieba_content_id_topic
  tiebaContentNoImageIdTopic: tieba_content_noimage_id_topic
spring:
  redis:
    database: 2
    host: 123.56.118.135
    password: gaoguangjin
    pool.max-active: 50000
    pool.max-idle: 500
    pool.max-wait: 1000
    pool.min-idle: 300
    port: 6379
    timeout: 100000
  datasource:
      name: database
      #url: jdbc:mysql://110.173.28.188:3306/master?useUnicode=true&characterEncoding=utf-8
      #username: slave
      #password: mobile
      url: jdbc:mysql://123.56.118.135:3306/master?useUnicode=true&characterEncoding=utf-8
      username: mobile
      password: mobile
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQueryTimeout: 900000
      validationQuery: SELECT SYSDATE() from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

qiniu:
  accessKey: aL-Y877Xpt0daNLqkule0TwNTsAFWR0aoYHUTRaA
  secretKey: ngCEeu-AABo_d5GdGJ076bUNSBsntAyisPPeB9ed
  #ggj2010 ggjqn
  bucketName: ggjqn
  domain: http://o8c5x5dg6.bkt.clouddn.com/
  